version: 2.1

orbs:
  singularity: singularity/singularity@1.0.2

jobs:
  build:
    docker:
    - image: circleci/python:3.6.2-stretch-browsers
    - run:
        name: Test AmrPlusPlus
        command: |
          if [ -f \\\"$BASH_ENV\\\" ]; then source $BASH_ENV; fi
          sudo apt-get update
          curl -fsSL get.nextflow.io | bash
          #/usr/local/bin/nextflow -h
          #singularity --version
          #git clone https://github.com/meglab-metagenomics/amrplusplus_v2.git
          #cd amrplusplus_v2/
          #nextflow run main_amr_plus_plus_v2_onlyAMR.nf -profile singularity --output test

workflows:
  build-and-deploy:
    jobs:
      - build
