version: 2.1
 
orbs:
  singularity: singularity/singularity@1.0.2

jobs:
  get_nextflow:
    docker:
    - image: circleci/node:4.8.2-jessie
    steps:
    - run:
        name: Install nextflow
        command: |
          curl -fsSL get.nextflow.io | bash
          ls
  get_singularity:
    docker:
    - image: singularityware/singularity:3.1-slim
    steps:
    - run:
        name: Check singularity version
        command: |
          if [ -f \\\"$BASH_ENV\\\" ]; then source $BASH_ENV; fi
          singularity --version
    


workflows:         
  build-and-deploy:
    jobs:
      - get_nextflow
      - get_singularity
