version: 2.1
 
orbs:
  singularity: singularity/singularity@1.0.2

jobs:
  get_singularity:
    docker:
    - image: singularityware/singularity:3.1-slim
    steps:
    - run:
        name: Check singularity version
        command: |
          if [ -f \"$BASH_ENV\" ]; then source $BASH_ENV; fi
          singularity --version
  get_nextflow:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - run:
        name: Install nextflow
        command: |
          curl -fsSL get.nextflow.io | bash
          ls
    


workflows:         
  build-and-deploy:
    jobs:
      - get_singularity
      - get_nextflow
