version: 2.1

orbs:
  singularity: singularity/singularity@dev:alpha

jobs:
  build:
    executor: singularity/machine
    parameters:
        singularity:
          type: string
          description: "Singularity version"
        singularity-3:
          type: boolean
          description: "Set to true for singularity 3, false for singularity 2"
          default: true
    machine: true
    steps:
    - checkout
    # Install Singularity
    - singularity/install-go:
        go-version: 1.11.5
    - singularity/debian-install-3:
        singularity-version: 3.2.1
    - run:
        name: Check install version
        command: |
          if [ -f "$BASH_ENV" ]; then source $BASH_ENV; fi
          echo "Test"
          
          
  test:
    machine: true
    executor: singularity/machine
    steps:
    - run:
        name: Test AmrPlusPlus pipeline
        command: |
          echo "Test"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
