version: 2.1

orbs:
  singularity: singularity/singularity@1.0.2

jobs:
  get_nextflow:
    docker:
    - image: buildpack-deps:trusty
    steps:
    - run:
        name: Install nextflow
        command: |
          if [ -f \\\"$BASH_ENV\\\" ]; then source $BASH_ENV; fi
          ls /bin/
          ls /usr/lib/
          curl -fsSL get.nextflow.io | bash
          nextflow -h
  deploy:
    docker:
    - image: singularityware/singularity:3.1-slim
    steps:
    - run:
        name: Check singularity version
        command: |
          if [ -f \\\"$BASH_ENV\\\" ]; then source $BASH_ENV; fi
          singularity --version



workflows:
  build-and-deploy:
    jobs:
      - get_nextflow
      - deploy:
           requires:
             - get_nextflow



----------------------------------------------

version: 2.1

orbs:
  singularity: singularity/singularity@1.0.2

jobs:
  build:
    docker:
    - image: buildpack-deps:trusty
    - image: nextflow/nextflow
    steps:
    - checkout
    - run:
        name: Check nextflow
        command: |
          if [ -f \\\"$BASH_ENV\\\" ]; then source $BASH_ENV; fi
          /usr/local/bin/nextflow -h

  deploy:
    docker:
    - image: buildpack-deps:trusty
    - image: singularityware/singularity:3.1-slim
    steps:
    - checkout
    - run:
        name: Test AmrPlusPlus
        command: |
          singularity --version
          git clone https://github.com/meglab-metagenomics/amrplusplus_v2.git
          cd amrplusplus_v2/
          /usr/local/bin/nextflow run main_amr_plus_plus_v2_onlyAMR.nf -profile singularity --output test




workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
           requires:
             - build
