version: 2.1

orbs:
  singularity: singularity/singularity@1.0.2

jobs:
  build:
    docker:
    - image: circleci/golang:1.9-browsers
    - image: singularityware/singularity:3.1-slim
    steps:
    - checkout
    - run:
        name: Test AmrPlusPlus
        command: |
          if [ -f \\\"$BASH_ENV\\\" ]; then source $BASH_ENV; fi
          singularity --version
          curl -fsSL https://get.nextflow.io | bash
          git clone https://github.com/meglab-metagenomics/amrplusplus_v2.git
          cd amrplusplus_v2/
          ../.nextflow run main_amr_plus_plus_v2_onlyAMR.nf -profile singularity --output test

workflows:
  build-and-deploy:
    jobs:
      - build
