version: 2.1
 
orbs:
  singularity: singularity/singularity@1.0.2

jobs:
  build:
    docker:
    - image: buildpack-deps:trusty
    - image: singularityware/singularity:3.1-slim
    - image: nextflow/nextflow
    steps:
    - checkout
    - run:
        name: install dockerize
        command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
        environment:
          DOCKERIZE_VERSION: v0.3.0
    - run:
        name: Wait for db
        command: dockerize -wait tcp://db:5432 -wait http://localhost:80 -timeout 5m
    - run:
        name: Test Run
        command: |
          if [ -f \\\"$BASH_ENV\\\" ]; then source $BASH_ENV; fi
          /usr/local/bin/nextflow -h
          singularity --version
          git clone https://github.com/meglab-metagenomics/amrplusplus_v2.git
          cd amrplusplus_v2/
          nextflow run main_amr_plus_plus_v2_onlyAMR.nf -profile singularity --output test
          
    


workflows:         
  build-and-deploy:
    jobs:
      - build
