version: 2.1
 
orbs:
  singularity: singularity/singularity@1.0.2

jobs:
  build:
    docker:
    - image: nextflow/nextflow
    - image: singularityware/singularity:3.1-slim
    steps:
    - run:
        name: Check singularity version
        command: |
          if [ -f \\\"$BASH_ENV\\\" ]; then source $BASH_ENV; fi
          /usr/local/bin/nextflow -h
          singularity --version
    


workflows:         
  build-and-deploy:
    jobs:
      - build
