version: 2
description: |
  Install Singularity 3.* on a debian base. We must first install GoLang.
  This is slower than using a pre-built container base, but gives us a native
  install with more functionality.
executor: machine
parameters:
  singularity-version:
    type: string
    default: 3.2.1
  go-version:
    type: string
    default: 1.11.5
  machine-type:
    type: string
    default: machine


jobs:
  build:
    machine: true
    steps:
    - install-go:
        go-version: <<parameters.go-version>>
    - debian-install-3:
        singularity-version: <<parameters.singularity-version>>
        machine-type: <<parameters.machine-type>>
    - run:
        name: Check install version
        command: |
          if [ -f "$BASH_ENV" ]; then source $BASH_ENV; fi
          singularity --version
  test:
    machine: true
    steps:
    - run:
        name: Test AmrPlusPlus pipeline
        command: |
          echo "Test"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
