version: 2.1
 
orbs:
  singularity: singularity/singularity@1.0.2

jobs:
  build:
    machine:
    - image: ubuntu-1604:201903-01
    steps:
    - run:
        name: Download Nextflow 
        command: |
          curl -fsSL get.nextflow.io | bash  
    
  deploy:
    docker:
    - image: singularityware/singularity:3.1-slim
    steps:
    - run:
        name: Check singularity version
        command: |
          if [ -f \"$BASH_ENV\" ]; then source $BASH_ENV; fi
          singularity --version
          ls
    
workflows:         
  build-and-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
