version: 2.1
description: |
  Install Singularity 3.* on a debian base. We must first install GoLang.
  This is slower than using a pre-built container base, but gives us a native
  install with more functionality.
executor: machine
parameters:
  singularity-version:
    type: string
    default: 3.2.1
  go-version:
    type: string
    default: 1.11.5
  machine-type:
    type: string
    default: machine

jobs:
  build:
    steps:
      - install-go:
          go-version: <<parameters.go-version>>
      - debian-install-3:
          singularity-version: <<parameters.singularity-version>>
          machine-type: <<parameters.machine-type>>
      - run:
          name: Check install version
          command: |
            if [ -f "$BASH_ENV" ]; then source $BASH_ENV; fi
            singularity --version
  test:
    steps:
      - Try_pipeline:
          name: Run AmrPlusPlus
          command: echo "TEST"
     
workflows:
  build-and-deploy:
    jobs:
      - singularity/install_debian_3:
          go-version: 1.11.5
          singularity-version: 3.2.1
      - build:
      - test:
        requires:
          - build
