description: |
  Install Singularity 3.* on a debian base. We must first install GoLang.
  This is slower than using a pre-built container base, but gives us a native
  install with more functionality.
executor: machine
parameters:
  singularity-version:
    type: string
    default: 3.2.1
  go-version:
    type: string
    default: 1.11.5
  machine-type:
    type: string
    default: machine
steps:
  - install-go:
      go-version: <<parameters.go-version>>
  - debian-install-3:
      singularity-version: <<parameters.singularity-version>>
      machine-type: <<parameters.machine-type>>
  - run:
      name: Check install version
      command: |
        if [ -f "$BASH_ENV" ]; then source $BASH_ENV; fi
        singularity --version
