version: 2.1

orbs:
  singularity: singularity/singularity@1.0.0

jobs:
  - singularity/install_debian_3:
    go-version: 1.11.5
    singularity-version: 3.2.1
    from-uri: docker://busybox
    image: busybox.sif
  build:
    machine: true
    steps:
    - run:
        name: Check install version
        command: |
          if [ -f "$BASH_ENV" ]; then source $BASH_ENV; fi
          echo "Test"
          
  test:
    machine: true
    executor: singularity/machine
    steps:
    - run:
        name: Test AmrPlusPlus pipeline
        command: |
          echo "Test"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
