version: 2.1

orbs:
  singularity: singularity/singularity@1.0.0
  
  
workflows:
  install_debian_3_example:
    jobs:
      - build:
      - test:
        requires:
          - build

jobs:
  build:
    docker:
      - image: debian:stretch
          - singularity/install_debian_3:
          go-version: 1.11.5
          singularity-version: 3.2.1
    steps:
      - singularity/install-go:
          go-version: 1.11.5

      - run:
          name: install nextflow
          command: curl -s https://get.nextflow.io | bash
            chmod u+x nextflow
  test:
    steps:
      - run:
          name: Test
          command: echo "Test,Test"
