version: 2
description: |
  Install Singularity 3.* on a debian base. We must first install GoLang.
  This is slower than using a pre-built container base, but gives us a native
  install with more functionality.
executor: machine
parameters:
  singularity-version:
    type: string
    default: 3.2.1
  go-version:
    type: string
    default: 1.11.5
  machine-type:
    type: string
    default: machine


jobs:
  build:
    parameters:
        singularity:
          type: string
          description: "Singularity version"
        singularity-3:
          type: boolean
          description: "Set to true for singularity 3, false for singularity 2"
          default: true
    machine: true
    steps:
    - run:
        name: Check install version
        command: |
          if [ -f "$BASH_ENV" ]; then source $BASH_ENV; fi
          echo "Test"
    # Install Singularity
    - when:
        condition: << parameters.singularity-3 >>
        steps:
          - singularity/install-go:
              go-version: 1.11.5
          - singularity/debian-install-3:
                    singularity-version: << parameters.singularity >>
    - unless:
        condition: << parameters.singularity-3 >>
        steps:
          - singularity/debian-install-2:
                    singularity-version: << parameters.singularity >>
          
          
  test:
    machine: true
    steps:
    - run:
        name: Test AmrPlusPlus pipeline
        command: |
          echo "Test"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
