version: 2.1
 
orbs:
  singularity: singularity/singularity@1.0.2

jobs:
  build:
    docker:
    - image: buildpack-deps:trusty
    - image: nextflow/nextflow
    - image: singularityware/singularity:3.1-slim
    steps:
    - checkout
    - run:
        name: install dockerize
        command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
        environment:
          DOCKERIZE_VERSION: v0.3.0
    - run:
        name: Wait for db
        command: dockerize -wait tcp://localhost:5432 -timeout 1m
    - run:
        name: Test Run
        command: |
          if [ -f \\\"$BASH_ENV\\\" ]; then source $BASH_ENV; fi
          /usr/local/bin/nextflow -h
          singularity --version
    


workflows:         
  build-and-deploy:
    jobs:
      - build
